// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEfXHOWNAslIQq2Ic9FdmW8XhQjq46JUw',
    appId: '1:726419909746:web:3212e045715388e99e66eb',
    messagingSenderId: '726419909746',
    projectId: 'vandana-ed800',
    authDomain: 'vandana-ed800.firebaseapp.com',
    storageBucket: 'vandana-ed800.firebasestorage.app',
    measurementId: 'G-QFKXMY0PKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT-kAAYpBNDFV-Tsd9Is49xqlVNvYcGIY',
    appId: '1:726419909746:android:a58f8467ebd9a8d89e66eb',
    messagingSenderId: '726419909746',
    projectId: 'vandana-ed800',
    storageBucket: 'vandana-ed800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlHLtvuvLSm6rgwoxwddM53rxxGmXJ9FI',
    appId: '1:726419909746:ios:b4a8a27a14c06ecf9e66eb',
    messagingSenderId: '726419909746',
    projectId: 'vandana-ed800',
    storageBucket: 'vandana-ed800.firebasestorage.app',
    iosBundleId: 'com.example.ashaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlHLtvuvLSm6rgwoxwddM53rxxGmXJ9FI',
    appId: '1:726419909746:ios:b4a8a27a14c06ecf9e66eb',
    messagingSenderId: '726419909746',
    projectId: 'vandana-ed800',
    storageBucket: 'vandana-ed800.firebasestorage.app',
    iosBundleId: 'com.example.ashaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEfXHOWNAslIQq2Ic9FdmW8XhQjq46JUw',
    appId: '1:726419909746:web:6415a646d19e7a059e66eb',
    messagingSenderId: '726419909746',
    projectId: 'vandana-ed800',
    authDomain: 'vandana-ed800.firebaseapp.com',
    storageBucket: 'vandana-ed800.firebasestorage.app',
    measurementId: 'G-F1PVD4R2M7',
  );
}
